import { request } from '@/service';
export async function fetchTransaction<R>(id: string) {
  return await request<R>(`
   {
 txs(
      pagination: {
        page_no: 1
        page_size:1
      }
      where:{
        txid:"${id}"
         show_sats:true
      }
    ) 
{
      items {    
        txid
        fee
        fee_rate
        sats
        block_height
        block_time
        vin
        {
          address
          btc
          txid
          balances
          {
            div_amount
          }
        }
        vout
        {
          address
          btc
          txid
          balances
          {
            div_amount
          }
        }
                stake_data
      {
        stake
        {
          detail
          {
            version
            stake
            {
              value
              type
              {
                text
                value
              }
            }
            reward
            {
              value
              type
              {
                text
                value
              }
            }
            index
          }
          pubkey
          network
          {
            bech32
            bip32
            {
              public
              private
            }
            pubKeyHash
            scriptHash
            wif
          }
          lock_time
        }
        script
        address
      }
      claim_data
      {
        is_claim
        stake_tx_id
        stake_vout
      }
      }
    }
  }
  `);
}
