name: Deploy

on:
  push:
    branches:
      - master

permissions:
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: 'npm'

      - name: Run Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build project
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url:  'https://viking-runes.github.io'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4