name: Deploy Test

on:
  push:
    branches:
      - test

permissions:
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    environment:
      name: github-pages-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
          cache: 'npm'

      - run: cp .env.testnet .env

      - name: Run Install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build project
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - run: cp dist/index.html dist/404.html

      - run: cp CNAME_test dist/CNAME

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: dist/
          destination-github-username: 'viking-runes'
          destination-repository-name: 'testnet.vikingrunes.io'
          user-email: viking.astross@gmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
